# ================================
# SERVER CONFIG
# ================================
server.port=8080

# ================================
# DATABASE CONFIG (PostgreSQL)
# ================================
spring.datasource.url=jdbc:postgresql://marinelink-db:5432/marinelink
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ================================
# JWT SECRET
# ================================
jwt.secret=2di0k30xPxh7s9LP7hAJSfMFX8y5BgeW5uLAe1rwpg4=

# ================================
# CORS CONFIG
# ================================
spring.web.cors.allow-credentials=true
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*
